package com.example.textanalysisapp.utils;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Map;

public class ExportUtils {

    public static void exportToTxt(Map<String, Object> results, File file) throws IOException {
        try (FileWriter writer = new FileWriter(file)) {
            writer.write(generateTxtContent(results));
        }
    }

    public static void exportToCsv(Map<String, Object> results, File file) throws IOException {
        try (FileWriter writer = new FileWriter(file)) {
            writer.write(generateCsvContent(results));
        }
    }

    private static String generateTxtContent(Map<String, Object> results) {
        StringBuilder sb = new StringBuilder();
        sb.append("=".repeat(60)).append("\n");
        sb.append("TEXT ANALYSIS REPORT\n");
        sb.append("=".repeat(60)).append("\n\n");

        sb.append("File Information:\n");
        sb.append("-".repeat(30)).append("\n");
        sb.append("File: ").append(results.get("fileName")).append("\n");
        sb.append("Size: ").append(results.get("fileSize")).append("\n\n");

        sb.append("Text Statistics:\n");
        sb.append("-".repeat(30)).append("\n");
        addStat(sb, "Total Words", results.get("totalWords"));
        addStat(sb, "Unique Words", results.get("uniqueWords"));
        addStat(sb, "Characters (with spaces)", results.get("charsWithSpaces"));
        addStat(sb, "Characters (no spaces)", results.get("charsWithoutSpaces"));
        addStat(sb, "Sentences", results.get("sentenceCount"));
        addStat(sb, "Paragraphs", results.get("paragraphCount"));
        addStat(sb, "Reading Time", results.get("readingTime") + " minutes");
        addStat(sb, "Sentiment", results.get("sentiment"));
        addStat(sb, "Average Word Length", results.get("avgWordLength"));
        addStat(sb, "Longest Word", results.get("longestWord"));

        sb.append("\nMost Frequent Words:\n");
        sb.append("-".repeat(30)).append("\n");
        sb.append(results.get("mostFrequent")).append("\n");

        sb.append("\n").append("=".repeat(60)).append("\n");
        sb.append("Generated by VioletLens Text Analyzer\n");
        sb.append("=".repeat(60)).append("\n");

        return sb.toString();
    }

    private static String generateCsvContent(Map<String, Object> results) {
        StringBuilder sb = new StringBuilder();
        sb.append("Metric,Value\n");

        addCsvRow(sb, "File Name", results.get("fileName"));
        addCsvRow(sb, "Total Words", results.get("totalWords"));
        addCsvRow(sb, "Unique Words", results.get("uniqueWords"));
        addCsvRow(sb, "Characters (with spaces)", results.get("charsWithSpaces"));
        addCsvRow(sb, "Characters (no spaces)", results.get("charsWithoutSpaces"));
        addCsvRow(sb, "Sentences", results.get("sentenceCount"));
        addCsvRow(sb, "Paragraphs", results.get("paragraphCount"));
        addCsvRow(sb, "Reading Time", results.get("readingTime") + " minutes");
        addCsvRow(sb, "Sentiment", results.get("sentiment"));
        addCsvRow(sb, "Average Word Length", results.get("avgWordLength"));
        addCsvRow(sb, "Longest Word", results.get("longestWord"));
        addCsvRow(sb, "File Size", results.get("fileSize"));

        return sb.toString();
    }

    private static void addStat(StringBuilder sb, String label, Object value) {
        if (value != null) {
            sb.append("• ").append(label).append(": ").append(value).append("\n");
        }
    }

    private static void addCsvRow(StringBuilder sb, String metric, Object value) {
        String escapedValue = value != null ? escapeCsv(value.toString()) : "";
        sb.append(escapeCsv(metric)).append(",").append(escapedValue).append("\n");
    }

    private static String escapeCsv(String value) {
        if (value == null) return "";
        if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }
}